BuildFire/communityWall

control/settings/controllers/mainSettingsCtrl.js
control/settings/views/mainSettings.html
widget/app.service.js
widget/assets/js/shared/stringsConfig.js
widget/controllers/widget.wall.controller.js
widget/index.html
widget/templates/thread.html

https://app.asana.com/0/503101155812087/1199546063307461/f
https://app.asana.com/0/503101155812087/1199520621228349/f
https://app.asana.com/0/503101155812087/1199557747352445/f
https://app.asana.com/0/1198193472666509/1199546344065189/f

3 bug fixes + 1 enhancement

---

widget/assets/css/style.css
widget/controllers/widget.thread.controller.js
widget/templates/thread.html

ticket link: https://app.asana.com/0/503101155812087/1199589541232069/f
Screenshots (before & after):

images in comments cut off fix

---

widget/controllers/widget.members.controller.js

https://app.asana.com/0/503101155812087/1199529568665672/f

refactor check for disabled private chat

---

widget/app.service.js
widget/controllers/widget.wall.controller.js

https://app.asana.com/0/1198193472666509/1199569646973779/f

prevent input api opening if there is no posts

---

control/content/controllers/content.home.controller.js
control/content/templates/home.html
plugin.json
widget/controllers/widget.members.controller.js
widget/controllers/widget.thread.controller.js
widget/controllers/widget.wall.controller.js
widget/index.html
widget/templates/members.html
widget/templates/thread.html

https://app.asana.com/0/503101155812087/1199558789074785/f

make order for user names and update all user data

---

widget/controllers/widget.wall.controller.js

- Social Inbox thread not created bug fix.
https://buildfire.atlassian.net/browse/PLUGINS-194

Social Inbox thread not created bug fix.

---

control/content/controllers/content.home.controller.js

https://buildfire.atlassian.net/browse/PLUGINS-365

fix: images showing randomly on not corresponding posts

---

widget/controllers/widget.thread.controller.js

https://buildfire.atlassian.net/browse/CS-203

fix: users able to delete others posts on thread wall

---

widget/controllers/widget.wall.controller.js

https://buildfire.atlassian.net/browse/CS-209

fix: show messages in PSW inbox

---

widget/app.service.js

https://buildfire.atlassian.net/browse/CS-610

fix: get wall id on back button

---

control/content/controllers/content.home.controller.js
widget/app.service.js
widget/controllers/widget.members.controller.js

- Fixing bad index searches (https://buildfire.atlassian.net/browse/CS-557)

Fixing bad index searches.

---

control/settings/views/mainSettings.html
plugin.json

JIRA ticket: https://buildfire.atlassian.net/browse/CS-620

fixed naming error inside settings tab

---

control/content/controllers/content.home.controller.js
widget/CommunityFeedAPI/dataAccess/Posts.js
widget/app.service.js

**Ticket** https://buildfire.atlassian.net/browse/CS-622

dev: Last Name Fix

---

widget/controllers/widget.wall.controller.js

https://buildfire.atlassian.net/browse/PT-3768

fix: private chats not subscribing targeted users

---

widget/controllers/widget.wall.controller.js

https://buildfire.atlassian.net/browse/PT-4764

fix: showing undefined as user name in private chats

---

control/content/controllers/content.home.controller.js
control/content/templates/home.html
widget/controllers/widget.thread.controller.js
widget/templates/thread.html

https://buildfire.atlassian.net/browse/CS-937

fix: iframes wont load

---

widget/CommunityFeedAPI/dataAccess/Posts.js

https://buildfire.atlassian.net/browse/PT-5041

fix: stop using email for showcase

---

widget/controllers/widget.thread.controller.js
widget/controllers/widget.wall.controller.js

Jira Ticket: https://buildfire.atlassian.net/browse/PT-4676

fixed %26 issue & replaced all decodeURI() to decodeURIComponent()

---

control/content/app.service.js
control/content/templates/home.html
widget/app.service.js
widget/controllers/widget.wall.controller.js
widget/index.html
widget/templates/thread.html

https://buildfire.atlassian.net/browse/PT-5155

fix: links not showing as anchors in post

---

widget/controllers/widget.wall.controller.js

https://buildfire.atlassian.net/browse/CS-1050

fix: private chats not opening through notification

---

control/content/controllers/content.home.controller.js
control/content/index.html
control/content/templates/home.html
package-lock.json
widget/CommunityFeedAPI/dataAccess/Posts.js
widget/controllers/widget.wall.controller.js
widget/index.html

- https://buildfire.atlassian.net/browse/PT-5551?atlOrigin=eyJpIjoiNjYxZjc4NjY2MjIzNDEyMmE1YjZiZTllMGRkM2VkNWIiLCJwIjoiaiJ9
- https://buildfire.atlassian.net/browse/PT-5565?atlOrigin=eyJpIjoiNjE0YjA4ZWQ4MjlkNDRlOTk5ODY1ZDE1MDkzYzg2YTEiLCJwIjoiaiJ9

Community Feed delete post bug fix & implement Read Less button.

---

widget/app.js
widget/app.service.js
widget/assets/css/inbox.css
widget/assets/css/privatechat.css
widget/assets/css/style.css
widget/controllers/widget.discover.controller.js
widget/controllers/widget.filtered.controller.js
widget/controllers/widget.inbox.controller.js
widget/controllers/widget.newPost.controller.js
widget/controllers/widget.privateChat.controller.js
widget/controllers/widget.profile.controller.js
widget/controllers/widget.singlePost.controller.js
widget/controllers/widget.wall.controller.js
widget/index.html
widget/templates/PrivateChat.html
widget/templates/discover.html
widget/templates/inbox.html
widget/templates/singlePost.html

-Videos not showing when entering through clicked/searched hashtags
-The post and Hashtags tab does not respond when navigating back and forth from the People tab
-Users profile image  is not shown in the inbox, only my profile image is shown
-Tagged Names when pressed take you to a single post view and names should pull text primary be separated by commas and last name by and
- On the emulator fill threshold is not shown in single post mode in my profile and tagged people are wrong color

fixes & enhancemens

---

widget/templates/thread.html

https://buildfire.atlassian.net/browse/PT-6244

fix: users not able edit/delete comment

---

control/content/app.service.js
control/content/controllers/content.home.controller.js
package-lock.json
widget/app.service.js
widget/controllers/widget.wall.controller.js

https://buildfire.atlassian.net/browse/CS-1246

fix indexing

---

control/content/index.html
widget/CommunityFeedAPI/data/analyticKeys.js
widget/CommunityFeedAPI/dataAccess/Posts.js
widget/app.service.js
widget/controllers/widget.wall.controller.js

1. Alt : post profile image.
2. Analytics :
- New post added
- New post deleted
- New post updated
- new post reported
- new post commented
- new post liked

add alt text to images & add analytics

---

control/settings/assets/css/sortable.css

https://buildfire.atlassian.net/browse/WEB2-767

Action Item Show Delete btn

---

control/content/controllers/content.home.controller.js

Fix missing indexes and search queries

Fix missing indexes

---

control/content/controllers/content.home.controller.js
control/content/templates/home.html
widget/app.service.js
widget/assets/js/shared/stringsConfig.js
widget/controllers/widget.thread.controller.js
widget/templates/thread.html

https://buildfire.atlassian.net/browse/APP2-3903

handle comments from deleted users

---

control/content/app.service.js
control/content/controllers/content.home.controller.js
control/content/index.html
widget/app.service.js

- [WL client unable to delete post on community wall](https://buildfire.atlassian.net/browse/WEB2-5160)
- [special characters like: # and @'s result in a percentage symbol when posting](https://buildfire.atlassian.net/browse/WEB2-5158)

Fix special chars and cp delete

---

widget/app.service.js
widget/index.html

add track posts by id to avoid re-rendering images when paginate

fix(widget): track posts - Ticket Number: PLUG-1744

---

widget/app.js

include the case of opening more groups pages and navigate back

fix(widget): back button click - PLUG-1823

---

widget/app.service.js
widget/controllers/widget.wall.controller.js
widget/index.html

fix missing data in the interval checking updated posts

fix(widget): interval getting posts - CS-2887

---

control/content/app.service.js
control/content/controllers/content.home.controller.js
widget/app.service.js
widget/assets/css/style.css
widget/controllers/widget.wall.controller.js
widget/index.html

send userIds in the queryString private notification, and handle the default appSettings data in widget

Fix/notification data - CS-2896

---

test/widget/controllers/widget.thread.controller.js
test/widget/controllers/widget.wall.controller.js
widget/app.service.js
widget/controllers/widget.thread.controller.js
widget/controllers/widget.wall.controller.js
widget/index.html
widget/templates/thread.html

Reverts BuildFire/communityWall#136

Revert "Fix/update performance - CS-3202"

---

widget/app.service.js
widget/controllers/widget.thread.controller.js
widget/controllers/widget.wall.controller.js

refactor updating posts performance  and sort private chat one to one wall id in the correct way

fix(update performance): refactor updating posts performance

---

widget/app.service.js
widget/controllers/widget.wall.controller.js

handle backward compatible for old broken data comming from other plugins

fix(deeplink): handle backward compatible for old broken data
